// <auto-generated />
using LittleLeagueFootball.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LittleLeagueFootball.Migrations
{
    [DbContext(typeof(LeagueContext))]
    partial class LeagueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LittleLeagueFootball.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Baker",
                            LastName = "Mayfield",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Chris",
                            LastName = "Godwin",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Mike",
                            LastName = "Evans",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Emeka",
                            LastName = "Egbuka",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Lavonte",
                            LastName = "David",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Rachaad",
                            LastName = "White",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Bucky",
                            LastName = "Irving",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Yaya",
                            LastName = "Diaby",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Sean",
                            LastName = "Tucker",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Cade",
                            LastName = "Otton",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Tyler",
                            LastName = "Allgeier",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Kyle",
                            LastName = "Pitts",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Darnell",
                            LastName = "Mooney",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Bijan",
                            LastName = "Robinson",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Micheal",
                            LastName = "Penix Jr.",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "AJ",
                            LastName = "Terrell",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Josh",
                            LastName = "Woods",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Chris",
                            LastName = "Blaire",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Khalid",
                            LastName = "Kareem",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Keith",
                            LastName = "Taylor",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Bryce",
                            LastName = "Young",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Trevor",
                            LastName = "Etienne",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Rico",
                            LastName = "Dowdle",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Ryan",
                            LastName = "Fitzgerald",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Chuba",
                            LastName = "Hubbard",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Xavier",
                            LastName = "Legette",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Tetairoa",
                            LastName = "McMillan",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Andy",
                            LastName = "Dalton",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Jalen",
                            LastName = "Coker",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Austin",
                            LastName = "Corbet",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Michael",
                            LastName = "Davis",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Alvin",
                            LastName = "Kamara",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Chris",
                            LastName = "Olave",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Terrell",
                            LastName = "Burgess",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Kendre",
                            LastName = "Miller",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Bub",
                            LastName = "Means",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Erik",
                            LastName = "McCoy",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Will",
                            LastName = "Sherman",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Dante",
                            LastName = "Pettis",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Ronnie",
                            LastName = "Bell",
                            TeamId = 4
                        });
                });

            modelBuilder.Entity("LittleLeagueFootball.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Buccaneers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Falcons"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Panthers"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Saints"
                        });
                });

            modelBuilder.Entity("LittleLeagueFootball.Models.Player", b =>
                {
                    b.HasOne("LittleLeagueFootball.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LittleLeagueFootball.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
